---
title: "Format Data"
author: "Richard Qiu"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
# Tidyverse MUST be loaded BEFORE Hmisc to avoid a function conflict with importing the data
# Tigris needed for FIPS codes
# Sjlabelled for dealing with labelled data

library(tigris)
library(sjlabelled)
library(readxl)
library(janitor)
library(stringr)
library(sjPlot)
library(gganimate)
library(tweenr)
library(tidyverse)
library(Hmisc)


# Load in data for FIPS codes from tigris
# distinct() essentially removes the county codes from the dataset
# Make state_code numeric and state_name lowercase to facilitate joining with other data

data(fips_codes)

fips <- 
  fips_codes %>% 
  distinct(state, state_code, state_name) %>%
  mutate(state_code = as.numeric(state_code),
         state_name = str_to_lower(state_name))


# Load in CDC National Immunization Survey data
# From https://www.cdc.gov/vaccines/imz-managers/nis/about.html
# Retrieved November 2018
# Created from .DAT files in .R scripts in /format_data/ folder
# Convert each RData object into a tibble

load("import_data/NISPUF12.RData")
load("import_data/NISPUF13.RData")
load("import_data/NISPUF14.RData")
load("import_data/NISPUF15.RData")
load("import_data/NISPUF16.RData")

raw_12 <- as_tibble(NISPUF12)
raw_13 <- as_tibble(NISPUF13)
raw_14 <- as_tibble(NISPUF14)
raw_15 <- as_tibble(NISPUF15)
raw_16 <- as_tibble(NISPUF16)


# Bind all years into a masive tibble, with each one ID'd by year
# Left join with fips codes to ID states

raw <- 
  bind_rows("2012" = raw_12,
            "2013" = raw_13,
            "2014" = raw_14,
            "2015" = raw_15,
            "2016" = raw_16,
            .id = "year") %>% 
  mutate(year = as.integer(year)) %>% 
  
  mutate(state_code = as.numeric(STATE)) %>% 
  left_join(fips, by= "state_code")



# Read in insurance data with custom col names 
# Data from US Census Bureau
# Retrieved from Table 6 from https://www.census.gov/library/publications/2017/demo/p60-260.html

# Decision to use Census Bureau elaborated on in explore.Rmd
# In summary, through the CDC survey asks for insurance coverage, only households with adequate healthcare provider information count are valid responses in the survey.
# As may be expected, the CDC numbers therefore skew high, and Census data is used in lieu

raw_insurance_cols <- c("state", "medicaid", "per_2013", "margin_2013", "per_2014", "margin_2014", "per_2015", "margin_2015", "per_2016", "margin_2016", "remove_1", "remove_2", "remove_3", "remove_4")
raw_insurance_per <- 
  read_excel("table6.xls", skip = 12, col_names = raw_insurance_cols) 


# Tidies up the raw Census Bureau insurance data
# Recode Medicaid expansion by year
# "y" represents medicaid expansion on January 1st for year in question
# Medicaid expansion dates confirmed with timeline from Henry J Kaiser Family Foundation 
# https://www.kff.org/medicaid/issue-brief/status-of-state-medicaid-expansion-decisions-interactive-map/

insurance_per <- 
  raw_insurance_per %>% 
  
  # Remove non-data rows
  
  remove_empty() %>% 
  slice(1:51) %>%
  
  # General formatting tweaks
  
  mutate(state = str_to_lower(str_remove_all(state, "[[:punct:]]")),
         medicaid = str_to_lower(medicaid)) %>% 
  select(-starts_with("remove"), -starts_with("margin")) %>% 

  # Make data tidy
  
  gather(year, per_ins, -state, -medicaid) %>% 
  mutate(year = str_remove(year, "per_"),
         year = as.integer(year),
         per_ins = 100 - per_ins) %>% 
  
  # Recode Medicaid info
  
  mutate(expansion_year = case_when(medicaid == "y" ~ 2014,
                                    medicaid == "^y" ~ 2015,
                                    medicaid == "+y" ~ 2016),
         medicaid = case_when(year >= expansion_year ~ "y",
                              year < expansion_year ~ "n",
                              is.na(expansion_year) ~ "n"))


# Read in Census Bureau population estimate data
# Data source: https://www.census.gov/data/tables/2017/demo/popest/state-total.html

raw_pop <- 
  read_csv("nst-est2017-alldata.csv") %>% 
  clean_names()


# Tidies up data and calculates population percentage
# Extracts only state-level summary data
# Excludes Puerto Rico 
# Chose to use only population estimates even though official record exists in 2010
# This is for consistency across years not in Census range

pop <- 
  raw_pop %>%
  
  # Select relavant data
  
  filter(sumlev == 40,
         region != "X") %>% 
  select(state, name, starts_with("popestimate")) %>% 
  mutate(name = str_to_lower(name)) %>% 
  
  # Tidy up data
  
  gather(year, pop, -state, -name) %>% 
  mutate(year = str_remove(year, "popestimate"),
         year = as.integer(year)) %>% 
  
  # Calculates population percentage by year
  
  group_by(year) %>% 
  mutate(per_pop = 100*pop/sum(pop))


# Read in historical poverty data from Census Bureau
# Source: https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html
# Only percentages extracted from Table 21 from relevant years

raw_pov <-
  read_excel("histpov.xlsx")

pov <- 
  


```



```{r vax_explore, echo = FALSE, include=FALSE}
vax_explore <- 
  raw %>% 
  
  group_by(year, state, state_code) %>% 
  count() %>% 
  ungroup() %>% 
  
  group_by(year) %>% 
  mutate(per_cdc = 100*n/sum(n)) %>% 
  
  left_join(pop, by = c("year" = "year", "state_code" = "state"))


ggplot(vax_explore, aes(x = per_cdc, y = per_pop, color = as.factor(year))) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0) +
  scale_color_brewer(palette = "Spectral") +
  scale_x_log10() + 
  scale_y_log10()
  theme_bw() +
  theme(aspect.ratio = 1)
  

```



```{r vax_recode}
# Relabel vaccinations into either adequate, incomplete, or none
# Based on CDC recommended immunization schedule
# Found here: https://www.cdc.gov/vaccines/schedules/easy-to-read/child-easyread.html

vax_recode <-
  raw %>% 
  
  # Removes responses w/o adequate vaccine provider info (essentially, no response since survey is provider based)
  
  filter(PDAT == 1) %>% 
  
  mutate(
         # There exist 2- and 3-dose vaccines for Rotavirus
         # Rotarix (GlaxoSmithKline) is 2-dose, RotaTeq (Merck) is 3-dose
         # Assumed that 1st vaccination dose is indicative of remainder of given vaccine schedule
         # i.e. if the first dose type is "RM" for "ROTATEQ (MERCK)" then the remainder of 
         # Rotavirus vaccines are also from Merck
         # Unknown vaccine brands assumed to be 2-dose
         # All Rotavirus vaccines should be completed before 19 months, no need to account for child age
    
         rota = case_when(P_NUMROT == 0 ~ "none",
                          P_NUMROT == 1 ~ "incomplete",
                          P_NUMROT == 2 & XROTTY1 == "RM" ~ "incomplete",
                          P_NUMROT == 2 & XROTTY1 == "RG" ~ "adequate",
                          P_NUMROT == 2 & XROTTY1 == "RO" ~ "adequate",
                          P_NUMROT >= 3 ~ "adequate"),
    
         # There exist both 2- and 3-dose vaccines for Hep A, but based on Rotavirus dose-vaccine matching,
         # No need to distinguish by dose--everyone who takes 2+ doses completes the vaccine schedule
         # Therefore, in the survey data, 2 doses and up counted as "adequate"
         # The first dose should be given before 23 months, with a second dose within 6 months of the 1st dose
         # Benefit of the doubt is given
         # i.e. the most generous possible binning combinations of age and vaccination
         # Status are used
         
         hepa = case_when(AGEGRP == 1 ~ "adequate",
                          AGEGRP == 2 & P_NUMHEA == 0 ~ "none",
                          AGEGRP == 2 & P_NUMHEA >= 1 ~ "adequate",
                          AGEGRP == 3 & P_NUMHEA == 0 ~ "none",
                          AGEGRP == 3 & P_NUMHEA == 1 ~ "incomplete",
                          AGEGRP == 3 & P_NUMHEA >- 2 ~ "adequate"),
         
         # There exist both 2- and 3-dose vaccines for Hep B; 2 doses and up counted as "adequate"
         # All childhood HepB vaccines shold be completed by 18 months, no need to account for child age
         # HepB detailed schedule found here: https://www.cdc.gov/mmwr/volumes/67/rr/pdfs/rr6701-H.PDF
         
         hepb = case_when(P_NUMHEP == 0 ~ "none",
                          P_NUMHEP == 1 ~ "incomplete",
                          P_NUMHEP >= 2 ~ "adequate"),
         
         # 4 doeses of DTap recommended by 18 months, with next dose after 36 months
         # Therfore, no need to account for child age at time of survey
         
         dtap = case_when(P_NUMDTP == 0 ~ "none",
                          P_NUMDTP > 0 & P_NUMDTP < 4 ~ "incomplete",
                          P_NUMDTP >= 4 ~ "adequate"),
         
         # 3 doses of IPV (polio vaccine) are recommended by age 18 months, no need to account for child age
         
         polio = case_when(P_NUMPOL == 0 ~ "none",
                           P_NUMPOL == 1 ~ "incomplete",
                           P_NUMPOL == 2 ~ "incomplete",
                           P_NUMPOL >= 3 ~ "adequate")
         
         )
  

```

```{r vax_year}
# Tidies up recoded vax data

vax_tidy <-
  vax_recode %>% 
  select(year, state, state_name, rota, hepa, hepb, dtap, polio) %>% 
  gather(vaccine, status, -year, -state, -state_name) 


# Summarizes by proportion of vaccinations at each level by year
# Status kept at 3 levels (rather than summing "incomplete"" and "inadequate") to allow for greater flexibility
# i.e. this can always be done after the fact

vax_year <-
  vax_tidy %>% 
  group_by(year, state, state_name) %>% 
  count(vaccine, status) %>% 
  group_by(year, state, state_name, vaccine) %>% 
  mutate(per_vax = 100*n/sum(n)) %>% 
  ungroup() %>% 
  select(-n)

```


```{r vax_factor}

vax_factor <-
  vax_year %>%
  
  # Filter out 2012 since no matching 2012 insurance data for now
  filter(year != 2012) %>% 
  
  left_join(insurance_per, by = c("state_name" = "state", "year")) %>% 
  ungroup()

write_rds(vax_factor, "App/vax_factor.rds")
```





```{r CDC_census_ins}

CDC_ins <-
  raw %>% 
  select(year, state_name, INS_STAT_I, PDAT) %>% 
  filter(year == 2016, PDAT == 1) %>% 
  mutate(cdc_ins = case_when(INS_STAT_I < 3 ~ "y",
                             TRUE ~ "n")) %>% 
  group_by(year, state_name) %>%
  count(cdc_ins) %>%
  mutate(CDC_per = 100*n/sum(n)) %>%
  filter(cdc_ins == "y") %>% 
  left_join(insurance_per, by = c("state_name" = "state", "year" = "year"))
  
CDC_ins %>% 
  ggplot(aes(x = per_ins, y = CDC_per)) + 
  geom_point() + 
  xlim(80, 100) + 
  ylim(80, 100) + 
  coord_fixed() +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_abline(slope = 1, intercept = 0)

summary(lm(CDC_per ~ per_ins, CDC_ins))


```


```{r}
polio_vax <- 
  vax_factor %>% 
  filter(vaccine == "polio", 
         status == "adequate",
         !is.na(medicaid)) %>% 
  mutate(color = recode(medicaid, "y" = "firebrick", 
                                  "n" = "steelblue"),
         colnum = recode(medicaid, "y" = 1, 
                                  "n" = 0),
         ease = "linear")

polio_edit <-
  polio_vax %>% 
  arrange(state_name, year) %>% 
  rename(x = per_ins, y = per_vax) %>% 
  mutate(ease = "linear")

polio_tween <-
  polio_vax %>% 
  tween_elements(time = "year", group = "state_name", ease = "ease", nframes = 60)

polio_vax %>% 
  ggplot(aes(x = per_ins, y = per_vax, color = colnum)) + 
     geom_point(size = 2) +
     scale_colour_identity() +
     theme_bw(base_size = 20) + 
     xlim(75, 100) + 
     ylim(60, 100) +
     transition_time(year) +
     labs(y = "Vaccination Rate", title = "Year: {frame_time}")


animate(g)  


vax_factor_model <- lm(per_vax ~ per_ins, polio_vax)

tab_model(vax_factor_model, show.intercept = FALSE, pred.labels = "Percent Insured", dv.labels = "Percent Vaccinated")

```





```{r measles_bf, echo=FALSE, include=FALSE}
measles_bf <-
  raw %>%
  select(BF_ENDR06, P_NUMMMR) %>% 
  filter(!is.na(BF_ENDR06) & !is.na(P_NUMMMR),
         P_NUMMMR != 3) %>% 
  mutate(BF_ENDR06 = as.numeric(BF_ENDR06),
         P_NUMMMR = as.factor(P_NUMMMR))

measles_bf %>% 
  ggplot(aes(x = P_NUMMMR, y = BF_ENDR06)) +
  geom_violin() + 
  geom_hline(aes(yintercept = 365)) +
  geom_hline(aes(yintercept = 365/2)) +
  geom_hline(aes(yintercept = 365*3/2))

```


```{r measles_income, echo=FALSE, include=FALSE}
measles_income <-
  raw %>% 
  transmute(income = as.factor(INCQ298A),
         measles = as.factor(P_NUMMMR)) %>% 
  filter(!is.na(measles), 
          measles != 3,
         !income %in% c(77,99))

write_rds(measles_income, "Rough/measles_income.rds")

measles_income %>% 
  ggplot(aes(x =income , fill = measles)) +
  geom_bar(position="fill")
```

```{r measles_insurace}
measles_insurance <-
  raw %>% 
  transmute(state_code, measles = as.factor(P_NUMMMR)) %>% 
  filter(measles %in% c(0, 1)) %>% 
  count(state_code, measles) %>% 
  left_join(fips, by = "state_code") %>% 
  select(-state_code, -state) %>% 
  left_join(insurance_per, by = c("state_name" = "state")) %>% 
  select(state_name, measles, n, per_2016) %>% 
  group_by(state_name) %>% 
  mutate(measles_per = n/sum(n),
         per_2016 = 100 - per_2016) %>% 
  filter(measles == 1)

ggplot(measles_insurance, aes(x = per_2016, y = measles_per)) +
  geom_point() +
  geom_smooth(method = "lm")


measles_insurace_lm <- lm(measles_per ~ per_2016, measles_insurance)
```


