---
title: "Immunizations"
author: "Richard Qiu"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
# Tidyverse MUST be loaded in before Hmisc to avoid a function conflict with importing the data
# Tigris needed for FIPS codes
# Sjlabelled for dealing with labelled data

library(tigris)
library(sjlabelled)
library(readxl)
library(janitor)
library(stringr)
library(tidyverse)
library(Hmisc)

# Load in data for FIPS codes from tigris
# distinct() essentially removes the county codes from the dataset
# Make state_code numeric and state_name lowercase to facilitate joining with other data

data(fips_codes)

fips <- 
  fips_codes %>% 
  distinct(state, state_code, state_name) %>%
  mutate(state_code = as.numeric(state_code),
         state_name = str_to_lower(state_name))


# Load in CDC immunization survey data
# Created from .DAT files in .R scripts in /format_data/ folder
# Convert each RData object into a tibble

load("NISPUF12.RData")
load("NISPUF13.RData")
load("NISPUF14.RData")
load("NISPUF15.RData")
load("NISPUF16.RData")

raw_12 <- as_tibble(NISPUF12)
raw_13 <- as_tibble(NISPUF13)
raw_14 <- as_tibble(NISPUF14)
raw_15 <- as_tibble(NISPUF15)
raw_16 <- as_tibble(NISPUF16)


# Bind all years into a masive tibble, with each one ID'd by year
# Left join with fips codes

raw <- 
  bind_rows("2012" = raw_12,
            "2013" = raw_13,
            "2014" = raw_14,
            "2015" = raw_15,
            "2016" = raw_16,
            .id = "year") %>% 
  mutate(state_code = as.numeric(STATE)) %>% 
  left_join(fips, by= "state_code")


# Add custom names for insurance data

raw_insurance_cols <- c("state", "medicaid", "per_2013", "margin_2013", "per_2014", "margin_2014", "per_2015", "margin_2015", "per_2016", "margin_2016", "remove_1", "remove_2", "remove_3", "remove_4")

raw_insurance_per <- 
  read_excel("table6.xls", skip = 12, col_names = raw_insurance_cols) 

insurance_per <- 
  raw_insurance_per %>% 
  remove_empty() %>% 
  mutate(state = str_to_lower(str_remove_all(state, "[[:punct:]]")),
         medicaid = str_to_lower(medicaid)) %>% 
  select(-starts_with("remove"), -starts_with("margin")) %>% 
  slice(1:51) %>% 
  gather(year, per, -state, -medicaid) %>% 
  mutate(year = str_remove(year, "per_"))
```



```{r}
state_counts <-
  raw %>% 
  select(STATE) %>% 
  count(STATE)
  

```



```{r exploration, echo = FALSE, include=FALSE}

temp <-
  raw %>%
  left_join(fips, by= "state_code") %>% 
  select(SEQNUMC, state) %>%
  slice(1:1000) %>%
  count(state) %>%
  mutate(expected = n*dim(raw)[1]/1000) %>% 
  arrange((expected))

temp
```

```{r measles_bf, echo=FALSE, include=FALSE}
measles_bf <-
  raw %>%
  select(BF_ENDR06, P_NUMMMR) %>% 
  filter(!is.na(BF_ENDR06) & !is.na(P_NUMMMR),
         P_NUMMMR != 3) %>% 
  mutate(BF_ENDR06 = as.numeric(BF_ENDR06),
         P_NUMMMR = as.factor(P_NUMMMR))

measles_bf %>% 
  ggplot(aes(x = P_NUMMMR, y = BF_ENDR06)) +
  geom_violin() + 
  geom_hline(aes(yintercept = 365)) +
  geom_hline(aes(yintercept = 365/2)) +
  geom_hline(aes(yintercept = 365*3/2))

```


```{r measles_income, echo=FALSE, include=FALSE}
measles_income <-
  raw %>% 
  transmute(income = as.factor(INCQ298A),
         measles = as.factor(P_NUMMMR)) %>% 
  filter(!is.na(measles), 
          measles != 3,
         !income %in% c(77,99))

write_rds(measles_income, "Rough/measles_income.rds")

measles_income %>% 
  ggplot(aes(x =income , fill = measles)) +
  geom_bar(position="fill")
```

```{r measles_insurace}
measles_insurance <-
  raw %>% 
  transmute(state_code, measles = as.factor(P_NUMMMR)) %>% 
  filter(measles %in% c(0, 1)) %>% 
  count(state_code, measles) %>% 
  left_join(fips, by = "state_code") %>% 
  select(-state_code, -state) %>% 
  left_join(insurance_per, by = c("state_name" = "state")) %>% 
  select(state_name, measles, n, per_2016) %>% 
  group_by(state_name) %>% 
  mutate(measles_per = n/sum(n),
         per_2016 = 100 - per_2016) %>% 
  filter(measles == 1)

ggplot(measles_insurance, aes(x = per_2016, y = measles_per)) +
  geom_point() +
  geom_smooth(method = "lm")


measles_insurace_lm <- lm(measles_per ~ per_2016, measles_insurance)
```


```{r}
write_rds(raw, "temp.rds")
```




